name: TSC_Disc_Proto
channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - wget=1.20.1
  - pip
  - pip:
      - tslearn==0.4.1
      - numpy==1.19.2
      - --requirement requirements.txt
